# Generated by Django 4.2.6 on 2023-11-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_id',
        ),
    ]
