# Generated by Django 4.2.6 on 2023-11-02 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useraccount_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
